language: node_js

services:
  - docker
  - mongodb

before_install:
  - docker pull mongo
  - docker run -d -p 27017:2001 mongo
  - docker container ls

install:
  - npm install
script:
  - yarn test
  - codecov
